### ISSUE TITLE
Changing existing AWS-Security-group of the running instances with playbook!

### ISSUE THREAD

**Issue by Murodbey** [Murodbey/AWX-project-playbooks#2]
Hello World!
I was successfully able to change ssh port of the running instance. However, if I need to ssh again to that machine, I had to open port "8875" on aws security group.  
I need to change the security group of the running instance.  Adding a port,  closing a port, etc. 
How I can achieve this? 
Thank you in advance!

```    
---
- name: ssh-port changing
  hosts: all
  #gather_facts: no
  remote_user: root
  tasks:
  - name: Setup alternate SSH port
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: "^Port"
      line: "Port 8875"
   # notify: "Restart sshd"

  - name: Setup SELinux for alternate SSH port
    seport:
      ports: "8875"
      proto: "tcp"
      setype: "ssh_port_t"
      state: "present"

  - name: Restart sshd
    service:
      name: sshd
      state: restarted
```
